apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
     app: db
spec:
  containers:
    - image: postgres
      name: db
      resources:
        limits:
          cpu: 0.5
      env:
        - name: DB_PASS
          value: Bubba1234!
        - name: POSTGRES_USER
          value: step-tracker
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
       - containerPort: 5432
         name: postgres
      volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-persistent-storage
      gcePersistentDisk:
        pdName: pg-db-disk
        fsType: ext4
              
